addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('GasolineriaIdlewood.txd',true)
engineImportTXD(txd, 5409)
local dff = engineLoadDFF('GasolineriaIdlewood.dff', 0)
engineReplaceModel(dff, 5409)
local col = engineLoadCOL('GasolineriaIdlewood.col')
engineReplaceCOL(col, 5409)
engineSetModelLODDistance(5409, 99999)
end)