addEventHandler('onClientResourceStart', resourceRoot,
function()
local txd = engineLoadTXD('CartelVinewood.txd',true)
engineImportTXD(txd, 13831)
local dff = engineLoadDFF('CartelVinewood.dff', 0)
engineReplaceModel(dff, 13831)
local col = engineLoadCOL('CartelVinewood.col')
engineReplaceCOL(col, 13831)
local dff = engineLoadDFF('BaseCartelVinewood.dff', 0)
engineReplaceModel(dff, 13722)
local col = engineLoadCOL('BaseCartelVinewood.col')
engineReplaceCOL(col, 13722)
engineSetModelLODDistance(13722, 99999)
end)